dist: trusty
sudo: false

language: python

python:
  - "2.7"

services:
  - postgresql
  - redis

install: pip install -r requirements.txt

before_script:
  - python manage.py init_db --create-db

script: pytest
