dist: trusty
sudo: false

language: python

python:
  - "2.7"

services:
  - postgresql
  - redis

addons:
  postgresql: 9.5

install: 
  - pip install git+https://github.com/metabrainz/messybrainz-server.git
  - pip install -r requirements.txt

before_script:
  - python manage.py init_db --create-db

script: py.test

cache: pip
